### ISSUE TITLE
How to generate item_db.js file

### ISSUE THREAD

**Issue by meannoharm** [misaomaki/misaomaki.github.io#8]
Nice project, but i have a quest.
How is the item_db.js file generated? I noticed there is a page for parsing Fandom, but is the resulting parse manually concatenated?

**Comment by misaomaki** [comment]
Thanks!

Yes, a combination of using the parser and just manually adding. Parsed from maplewiki by copying the page source into the textbox in the parser. It's parsed usually by item category and concatenated to item_db.js.

The parser has issues as it has trouble downloading the image files, and it doesn't work with all maplewiki pages since the data is pretty dirty, but works "okay" enough and requires manual clean up.

**Comment by meannoharm** [comment]
Thanks for the reply

What a tremendous job!
